#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/tests/lib/helpers.sh"
agent="$ROOT/.github/workflows/agent-dispatch.yml"
review="$ROOT/.github/workflows/review-repair.yml"
common="$ROOT/scripts/lib/common.sh"
runner_check="$ROOT/scripts/check-runner-availability.mjs"

line_of() { grep -nF "$2" "$1" | head -1 | cut -d: -f1; }
authorize_line="$(line_of "$agent" 'Authorize actor before control-plane preflight')"
runner_line="$(line_of "$agent" 'Check compatible self-hosted runner availability')"
budget_line="$(line_of "$agent" 'Check paid provider budget')"
route_line="$(line_of "$agent" 'Resolve execution route')"
self_line="$(line_of "$agent" 'Agent Dispatch (self-hosted isolated)')"
t "ordinary actor authorization precedes secret-bearing preflight" yes "$([ -n "$authorize_line" ] && [ "$authorize_line" -lt "$runner_line" ] && [ "$authorize_line" -lt "$budget_line" ] && echo yes || echo no)"
t "ordinary runner check precedes budget check" yes "$([ "$runner_line" -lt "$budget_line" ] && echo yes || echo no)"
t "ordinary budget check precedes route resolution" yes "$([ "$budget_line" -lt "$route_line" ] && echo yes || echo no)"
t "ordinary route resolves before self-hosted job" yes "$([ "$route_line" -lt "$self_line" ] && echo yes || echo no)"
t "self-hosted job is gated by route decision" yes "$(grep -q "route_decision == 'run-self-hosted'" "$agent" && echo yes || echo no)"
t "self-hosted runs-on comes from trusted route labels" yes "$(grep -q 'fromJSON(needs.route.outputs.runner_labels)' "$agent" && echo yes || echo no)"
t "hosted path remains dry-run only" yes "$(grep -q "route_decision.*github-dry-run\|runner_mode == 'github'.*dry_run == 'true'" "$agent" && echo yes || echo no)"
t "budget hard floor defaults to 0.25" yes "$(grep -q "PROVIDER_BALANCE_HARD_FLOOR_USD.*'0.25'" "$agent" && echo yes || echo no)"
t "budget warning defaults to 0.50" yes "$(grep -q "PROVIDER_BALANCE_WARN_USD.*'0.50'" "$agent" && echo yes || echo no)"
t "Phase A job reserve defaults to 0.25" yes "$(grep -q "PROVIDER_JOB_MAX_USD.*'0.25'" "$agent" && grep -q "PROVIDER_JOB_MAX_USD.*'0.25'" "$review" && echo yes || echo no)"
t "billing alerts receive required job reserve context" yes "$(grep -q 'budget_required_job_reserve_usd:' "$agent" && grep -q 'BUDGET_REQUIRED_JOB_RESERVE_USD:' "$agent" && [ "$(grep -c 'BUDGET_REQUIRED_JOB_RESERVE_USD:' "$review")" -ge 2 ] && echo yes || echo no)"
t "runner status API version is stable and explicit" yes "$(grep -q "X-GitHub-Api-Version.*2022-11-28" "$runner_check" && echo yes || echo no)"
t "provider management credentials stay out of agent container env" absent "$(grep -Eq '\-\-env OPENROUTER_MANAGEMENT_KEY' "$ROOT/scripts/run-agent-dispatch-container.sh" && echo present || echo absent)"
t "no OPENAI_ADMIN_KEY in composite" absent "$(grep -Eq 'OPENAI_ADMIN_KEY|RUNNER_STATUS_TOKEN' "$ROOT/.github/actions/agent-dispatch/action.yml" && echo present || echo absent)"
t "billing SMTP password stays out of untrusted composite" absent "$(grep -q 'BILLING_SMTP_PASSWORD' "$ROOT/.github/actions/agent-dispatch/action.yml" && echo present || echo absent)"
t "waiting states have dedicated feedback job" yes "$(grep -q 'post-route-waiting.sh' "$agent" && echo yes || echo no)"

same_runner="$(line_of "$review" 'Check compatible self-hosted executor availability')"
same_budget="$(line_of "$review" 'Check OpenRouter budget before review repair')"
same_gate="$(line_of "$review" 'Resolve review-repair preflight')"
reserve="$(line_of "$review" 'Reserve review id and attempt')"
t "same-repo repair runner preflight precedes budget" yes "$([ "$same_runner" -lt "$same_budget" ] && echo yes || echo no)"
t "same-repo repair budget precedes reserve" yes "$([ "$same_budget" -lt "$reserve" ] && echo yes || echo no)"
t "same-repo repair gate precedes reserve" yes "$([ "$same_gate" -lt "$reserve" ] && echo yes || echo no)"
t "repair attempt reserved only after preflight run decision" yes "$(grep -A3 'id: reserve' "$review" | grep -q "if: steps.gate.outputs.decision == 'run'" && echo yes || echo no)"
t "scheduled repair matrix requires runner and budget pass" yes "$(grep -A4 'id: matrix' "$review" | grep -q "steps.runner.outputs.decision == 'run'.*steps.budget.outputs.decision == 'pass'" && echo yes || echo no)"
t "cross-repo repair parallelism is bounded" yes "$(grep -q 'max-parallel: 1' "$review" && echo yes || echo no)"
t "budget categories are machine-readable" yes "$(grep -q 'CAT_PROVIDER_BUDGET_LOW="PROVIDER_BUDGET_LOW"' "$common" && grep -q 'CAT_PROVIDER_BUDGET_UNKNOWN="PROVIDER_BUDGET_UNKNOWN"' "$common" && echo yes || echo no)"
t "runner categories are machine-readable" yes "$(grep -q 'CAT_RUNNER_UNAVAILABLE="RUNNER_UNAVAILABLE"' "$common" && grep -q 'CAT_RUNNER_STATUS_UNKNOWN="RUNNER_STATUS_UNKNOWN"' "$common" && echo yes || echo no)"
finish
